### 1.Distance

In [11]:
import pandas as pd
import numpy as np
from scipy.spatial import distance_matrix

In [12]:
# Mocking Data
data = {
    "ID": ["P1,","P2,","P3,","P4,"],
    "x" : [0,2,3,5],
    "y" : [2,0,1,1],
}

In [13]:
print(data)

{'ID': ['P1,', 'P2,', 'P3,', 'P4,'], 'x': [0, 2, 3, 5], 'y': [2, 0, 1, 1]}


In [15]:
# แปลง Dictionary to DataFram
df = pd.DataFrame(data).set_index("ID")
df

x  y
ID       
P1,  0  2
P2,  2  0
P3,  3  1
P4,  5  1

In [23]:
# Manhattan
manhattan = distance_matrix(df.values, df.values,p = 1)

# Euclidian
euclidian = distance_matrix(df.values, df.values,p = 2)

# minkowsky p = 3
minkowsky = distance_matrix(df.values,df.values,p = 3)

In [24]:
print("manhattan\n",manhattan.round(3))
print("euclidian\n",euclidian.round(3))
print("minkowsky\n",minkowsky.round(3))

manhattan
 [[0. 4. 4. 6.]
 [4. 0. 2. 4.]
 [4. 2. 0. 2.]
 [6. 4. 2. 0.]]
euclidian
 [[0.    2.828 3.162 5.099]
 [2.828 0.    1.414 3.162]
 [3.162 1.414 0.    2.   ]
 [5.099 3.162 2.    0.   ]]
minkowsky
 [[0.    2.52  3.037 5.013]
 [2.52  0.    1.26  3.037]
 [3.037 1.26  0.    2.   ]
 [5.013 3.037 2.    0.   ]]
