# แบบฝึกหัด NumPy – การสร้างและใช้งานอาเรย์

In [37]:
import numpy as np
# 1. อาเรย์ 1 มิติ ที่มีเลขคี่จาก 1 ถึง 15 ขนาด 8 ตัว
array_1d = np.arange(1, 16, 2)
print("1D array:", array_1d)

1D array: [ 1  3  5  7  9 11 13 15]


In [38]:
# 2. อาเรย์ 2 มิติ ขนาด 3x5 ที่มีค่าเริ่มต้นเป็น 9
array_2d = np.full((3, 5), 9)
print("2D array:\n", array_2d)

2D array:
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [39]:
# 3. อาเรย์ 3 มิติ 2x3x4 ที่มีค่าเป็น 0 ทั้งหมด
array_3d = np.zeros((2, 3, 4))
print("3D array shape:", array_3d.shape)

3D array shape: (2, 3, 4)


In [40]:
# 4. ใช้ np.linspace สร้างอาเรย์ที่มี 10 ค่า จาก 0 ถึง 5
lin_array = np.linspace(0, 5, 10)
print("Linspace array:", lin_array)

Linspace array: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# แบบฝึกหัด: NumPy Indexing & Slicing
default_array = np.array([1, 2, 3, 4, 5, 6])
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [41]:
default_array = np.array([1, 2, 3, 4, 5, 6])
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [42]:
# 1. สมาชิกตัวสุดท้ายของ default_array
last_item = default_array[5]
print("Last item:", last_item)

Last item: 6


In [43]:
# 2. สมาชิกตั้งแต่ index 1–3
slice_2_to_4 = default_array[1:4]
print("Slice 2 to 4:", slice_2_to_4)

Slice 2 to 4: [2 3 4]


In [44]:
# 3. ค่าทั้งหมดในคอลัมน์ที่ 2 ของ default_array_2d
column_2 = default_array_2d[:, 1]
print("Column 2:", column_2)

Column 2: [ 2  6 10]


# แบบฝึกหัด 3: คำนวณ (x^2 + 2x) เมื่อ x = [1, 2, 3, 4]

In [45]:
# แบบฝึกหัด 3: คำนวณ (x^2 + 2x) เมื่อ x = [1, 2, 3, 4]
x = np.array([1, 2, 3, 4])
result = x**2 + 2*x
print("x^2 + 2x =", result)

x^2 + 2x = [ 3  8 15 24]
