## 1.import numpy as np เรียกใช้งาน numpy 

In [1]:
import numpy as np

In [ ]:
# Syntax creating Array
# array_name = np.array()

# 1 - dimensiona1 array 1,5,2,0 
arr_1d = np.array([ 1, 5, 2, 0 ])
# 2 - dimensional array  1,5,2,0  8,3,6,1  1,7,2,9
arr_2d = np.array([ [1,5,2,0], [8,3,6,1], [1,7,2,9] ])

# 3 - dimensional array 10, 15, 20, 25   30, 35, 40, 45   50, 55, 60, 65 
arr_3d = np.array([ [10, 15], 
                [ 20, 25], 
                
                [30, 35], 
                [40, 45],
                
                [50, 55], 
                [60, 65] ])

In [4]:
print(arr_1d)
print('-------')
print(arr_2d)

[1 5 2 0]
-------
[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]


In [9]:
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [11]:
# สามตัวแรก 
default_array[ :3]

# ตีวที่ 4 เป็นต้นไป 
# default_array[3:]

# สามชืกใน row 2 columns 4 
# default_array_2d[1,3]

array([1, 2, 3])

In [12]:
array_attribute = np.array([ [  1, 2, 3, 4 ], [  5, 6, 7, 8 ], [ 9, 10, 11, 12 ] ])

In [ ]:
# ตรวจสอบคุณสมบัติของ Array
# array_attribute.ndim
# array_attribute.ndim
# # array_attribute.shape
# array_attribute.shape 

In [14]:
zero_2d_array = np.zeros(2)
one_1d_array = np.ones(5)
arang_array = np.arange(4)
step_arang_array= np.arange(2,9,2)  # start stop step 

In [ ]:
# zero_2d_array
print()
# one_1d_array
# arang_array
# step_arang_array
print(one_1d_array)

In [15]:
array_sample = np.arange(20)

In [16]:
print(array_sample)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#   reshape สองแถว
array_sample.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])